# *folio theme
# Site settings
title: "svet's lab"
description: > # this means to ignore newlines until "baseurl:"
  A blog about the theoretical and the practical aspects of machine learning,
  artificial intelligence and robotics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://svepe.github.io" # the base hostname & protocol for your site
github_username: svepe

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  lablogs:
    output: true
    permalink: /lablogs/:path/
